import type { INodeProperties } from 'n8n-workflow';

export const contactOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['contact'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create a new contact',
				action: 'Create a contact',
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a contact by ID',
				action: 'Delete a contact',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get a contact by ID',
				action: 'Get a contact',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Retrieve a list of contacts',
				action: 'Get many contacts',
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update an existing contact',
				action: 'Update a contact',
			},
			{
				name: 'Batch Create',
				value: 'batchCreate',
				description: 'Create multiple contacts at once',
				action: 'Batch create contacts',
			},
			{
				name: 'Batch Delete',
				value: 'batchDelete',
				description: 'Delete multiple contacts by IDs',
				action: 'Batch delete contacts',
			},
		],
		default: 'getAll',
	},
];

export const contactFields: INodeProperties[] = [
	// ─── GET MANY ────────────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['contact'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 100 },
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['contact'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['contact'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Search across firstname, lastname, email, phone, company',
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				options: [
					{ name: 'Lead', value: 'lead' },
					{ name: 'Customer', value: 'customer' },
					{ name: 'Guest', value: 'guest' },
				],
				default: 'lead',
				description: 'Filter by contact type',
			},
			{
				displayName: 'Status ID',
				name: 'status_id',
				type: 'number',
				default: 0,
				description: 'Filter by status ID',
			},
			{
				displayName: 'Source ID',
				name: 'source_id',
				type: 'number',
				default: 0,
				description: 'Filter by source ID',
			},
			{
				displayName: 'Group ID',
				name: 'group_id',
				type: 'number',
				default: 0,
				description: 'Filter by group ID',
			},
			{
				displayName: 'Assigned User ID',
				name: 'assigned_id',
				type: 'number',
				default: 0,
				description: 'Filter by assigned user ID',
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'options',
				options: [
					{ name: 'Newest First', value: '-created_at' },
					{ name: 'Oldest First', value: 'created_at' },
					{ name: 'First Name A–Z', value: 'firstname' },
					{ name: 'First Name Z–A', value: '-firstname' },
					{ name: 'Last Name A–Z', value: 'lastname' },
					{ name: 'Last Updated', value: '-updated_at' },
				],
				default: '-created_at',
				description: 'Sort order for results',
			},
			{
				displayName: 'Include Relationships',
				name: 'include',
				type: 'multiOptions',
				options: [
					{ name: 'Groups', value: 'groups' },
					{ name: 'Source', value: 'source' },
					{ name: 'Status', value: 'status' },
				],
				default: [],
				description: 'Relationships to include in the response',
			},
		],
	},

	// ─── GET / UPDATE / DELETE ───────────────────────────────────────────────────
	{
		displayName: 'Contact ID',
		name: 'contactId',
		type: 'string',
		required: true,
		default: '',
		description: 'The ID of the contact',
		displayOptions: {
			show: { resource: ['contact'], operation: ['get', 'update', 'delete'] },
		},
	},

	// ─── GET – includes ──────────────────────────────────────────────────────────
	{
		displayName: 'Include Relationships',
		name: 'include',
		type: 'multiOptions',
		options: [
			{ name: 'Groups', value: 'groups' },
			{ name: 'Source', value: 'source' },
			{ name: 'Status', value: 'status' },
		],
		default: [],
		description: 'Relationships to include in the response',
		displayOptions: { show: { resource: ['contact'], operation: ['get'] } },
	},

	// ─── CREATE ──────────────────────────────────────────────────────────────────
	{
		displayName: 'First Name',
		name: 'firstname',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
	},
	{
		displayName: 'Last Name',
		name: 'lastname',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
	},
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string',
		required: true,
		default: '',
		description: 'Phone number with country code (e.g. +919876543210)',
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'options',
		required: true,
		options: [
			{ name: 'Lead', value: 'lead' },
			{ name: 'Customer', value: 'customer' },
			{ name: 'Guest', value: 'guest' },
		],
		default: 'lead',
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
	},
	{
		displayName: 'Source ID',
		name: 'source_id',
		type: 'number',
		required: true,
		default: 0,
		description: 'Source ID (must exist in your account)',
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
	},
	{
		displayName: 'Status ID',
		name: 'status_id',
		type: 'number',
		required: true,
		default: 0,
		description: 'Status ID (must exist in your account)',
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
		options: [
			{ displayName: 'Email', name: 'email', type: 'string', default: '' },
			{ displayName: 'Company', name: 'company', type: 'string', default: '' },
			{ displayName: 'Description', name: 'description', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'City', name: 'city', type: 'string', default: '' },
			{ displayName: 'State', name: 'state', type: 'string', default: '' },
			{ displayName: 'ZIP', name: 'zip', type: 'string', default: '' },
			{ displayName: 'Address', name: 'address', type: 'string', default: '' },
			{ displayName: 'Country ID', name: 'country_id', type: 'number', default: 0 },
			{ displayName: 'Assigned User ID', name: 'assigned_id', type: 'number', default: 0 },
			{
				displayName: 'Group IDs',
				name: 'groups',
				type: 'string',
				default: '',
				description: 'Comma-separated list of group IDs to assign',
			},
		],
	},

	// ─── UPDATE ──────────────────────────────────────────────────────────────────
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['contact'], operation: ['update'] } },
		options: [
			{ displayName: 'First Name', name: 'firstname', type: 'string', default: '' },
			{ displayName: 'Last Name', name: 'lastname', type: 'string', default: '' },
			{ displayName: 'Phone', name: 'phone', type: 'string', default: '' },
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				options: [
					{ name: 'Lead', value: 'lead' },
					{ name: 'Customer', value: 'customer' },
					{ name: 'Guest', value: 'guest' },
				],
				default: 'lead',
			},
			{ displayName: 'Source ID', name: 'source_id', type: 'number', default: 0 },
			{ displayName: 'Status ID', name: 'status_id', type: 'number', default: 0 },
			{ displayName: 'Email', name: 'email', type: 'string', default: '' },
			{ displayName: 'Company', name: 'company', type: 'string', default: '' },
			{ displayName: 'Description', name: 'description', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'City', name: 'city', type: 'string', default: '' },
			{ displayName: 'State', name: 'state', type: 'string', default: '' },
			{ displayName: 'ZIP', name: 'zip', type: 'string', default: '' },
			{ displayName: 'Address', name: 'address', type: 'string', default: '' },
			{ displayName: 'Country ID', name: 'country_id', type: 'number', default: 0 },
			{ displayName: 'Assigned User ID', name: 'assigned_id', type: 'number', default: 0 },
			{
				displayName: 'Group IDs',
				name: 'groups',
				type: 'string',
				default: '',
				description: 'Comma-separated list of group IDs (replaces existing assignments)',
			},
		],
	},

	// ─── BATCH CREATE ────────────────────────────────────────────────────────────
	{
		displayName: 'Contacts (JSON)',
		name: 'contacts',
		type: 'json',
		required: true,
		default: '[]',
		description: 'Array of contact objects to create. Each must have: firstname, lastname, phone, type, source_id, status_id.',
		displayOptions: { show: { resource: ['contact'], operation: ['batchCreate'] } },
	},
	{
		displayName: 'Options',
		name: 'batchOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['contact'], operation: ['batchCreate'] } },
		options: [
			{
				displayName: 'Continue on Error',
				name: 'continue_on_error',
				type: 'boolean',
				default: true,
				description: 'Whether to continue processing if one contact fails',
			},
			{
				displayName: 'Skip Duplicates',
				name: 'skip_duplicates',
				type: 'boolean',
				default: false,
				description: 'Whether to skip contacts with duplicate phone numbers',
			},
		],
	},

	// ─── BATCH DELETE ────────────────────────────────────────────────────────────
	{
		displayName: 'Contact IDs',
		name: 'ids',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated list of contact IDs to delete',
		displayOptions: { show: { resource: ['contact'], operation: ['batchDelete'] } },
	},
];
