import type { INodeProperties } from 'n8n-workflow';

export const messageOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['message'] } },
		options: [
			{
				name: 'Get',
				value: 'get',
				description: 'Get a message by ID',
				action: 'Get a message',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Retrieve message history',
				action: 'Get many messages',
			},
			{
				name: 'Send Text',
				value: 'sendText',
				description: 'Send a plain text WhatsApp message',
				action: 'Send a text message',
			},
			{
				name: 'Send Template',
				value: 'sendTemplate',
				description: 'Send a pre-approved WhatsApp template message',
				action: 'Send a template message',
			},
			{
				name: 'Send Media',
				value: 'sendMedia',
				description: 'Send an image, video, document, or audio message',
				action: 'Send a media message',
			},
			{
				name: 'Send Interactive',
				value: 'sendInteractive',
				description: 'Send a button or list interactive message',
				action: 'Send an interactive message',
			},
		],
		default: 'sendText',
	},
];

export const messageFields: INodeProperties[] = [
	// ─── GET MANY ────────────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['message'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 100 },
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['message'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Search within message text',
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				options: [
					{ name: 'Text', value: 'text' },
					{ name: 'Template', value: 'template' },
					{ name: 'Image', value: 'image' },
					{ name: 'Video', value: 'video' },
					{ name: 'Document', value: 'document' },
					{ name: 'Audio', value: 'audio' },
					{ name: 'Interactive', value: 'interactive' },
				],
				default: 'text',
				description: 'Filter by message type',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Sent', value: 'sent' },
					{ name: 'Delivered', value: 'delivered' },
					{ name: 'Read', value: 'read' },
					{ name: 'Failed', value: 'failed' },
				],
				default: 'sent',
				description: 'Filter by delivery status',
			},
			{
				displayName: 'Direction',
				name: 'direction',
				type: 'options',
				options: [
					{ name: 'Inbound', value: 'inbound' },
					{ name: 'Outbound', value: 'outbound' },
				],
				default: 'outbound',
				description: 'Filter by message direction',
			},
			{
				displayName: 'Interaction ID',
				name: 'interaction_id',
				type: 'number',
				default: 0,
				description: 'Filter by chat interaction ID',
			},
		],
	},

	// ─── GET ─────────────────────────────────────────────────────────────────────
	{
		displayName: 'Message ID',
		name: 'messageId',
		type: 'string',
		required: true,
		default: '',
		description: 'The internal ID of the message',
		displayOptions: { show: { resource: ['message'], operation: ['get'] } },
	},

	// ─── SEND TEXT ───────────────────────────────────────────────────────────────
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number with country code (e.g. +919876543210)',
		displayOptions: { show: { resource: ['message'], operation: ['sendText'] } },
	},
	{
		displayName: 'Message',
		name: 'message',
		type: 'string',
		required: true,
		typeOptions: { rows: 4 },
		default: '',
		description: 'Message text (max 4096 chars). Supports merge fields like @{contact_first_name}.',
		displayOptions: { show: { resource: ['message'], operation: ['sendText'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['sendText'] } },
		options: [
			{
				displayName: 'Contact ID',
				name: 'contact_id',
				type: 'number',
				default: 0,
				description: 'Existing contact ID (skips auto-creation lookup)',
			},
		],
	},

	// ─── SEND TEMPLATE ───────────────────────────────────────────────────────────
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number with country code',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
	},
	{
		displayName: 'Template Name',
		name: 'template_name',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of the approved WhatsApp template',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
	},
	{
		displayName: 'Language',
		name: 'language',
		type: 'string',
		required: true,
		default: 'en',
		description: 'Template language code (e.g. en, en_GB, hi)',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
	},
	{
		displayName: 'Template Parameters',
		name: 'templateParams',
		type: 'collection',
		placeholder: 'Add Parameter',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
		options: [
			{ displayName: 'Contact ID', name: 'contact_id', type: 'number', default: 0 },
			{ displayName: 'Body Field 1 ({{1}})', name: 'field_1', type: 'string', default: '' },
			{ displayName: 'Body Field 2 ({{2}})', name: 'field_2', type: 'string', default: '' },
			{ displayName: 'Body Field 3 ({{3}})', name: 'field_3', type: 'string', default: '' },
			{ displayName: 'Body Field 4 ({{4}})', name: 'field_4', type: 'string', default: '' },
			{ displayName: 'Body Field 5 ({{5}})', name: 'field_5', type: 'string', default: '' },
			{ displayName: 'Header Text Field', name: 'header_field_1', type: 'string', default: '', description: 'For TEXT header templates' },
			{ displayName: 'Header Image URL', name: 'header_image_url', type: 'string', default: '', description: 'For IMAGE header templates' },
			{ displayName: 'Header Video URL', name: 'header_video_url', type: 'string', default: '', description: 'For VIDEO header templates' },
			{ displayName: 'Header Document URL', name: 'header_document_url', type: 'string', default: '', description: 'For DOCUMENT header templates' },
			{ displayName: 'Header Document Name', name: 'header_document_name', type: 'string', default: '', description: 'Display name for document header' },
			{ displayName: 'Button 1 Parameter', name: 'button_0', type: 'string', default: '' },
			{ displayName: 'Button 2 Parameter', name: 'button_1', type: 'string', default: '' },
			{ displayName: 'Button 3 Parameter', name: 'button_2', type: 'string', default: '' },
		],
	},

	// ─── SEND MEDIA ──────────────────────────────────────────────────────────────
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number with country code',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
	},
	{
		displayName: 'Media Type',
		name: 'media_type',
		type: 'options',
		required: true,
		options: [
			{ name: 'Image', value: 'image' },
			{ name: 'Document', value: 'document' },
			{ name: 'Video', value: 'video' },
			{ name: 'Audio', value: 'audio' },
		],
		default: 'image',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
	},
	{
		displayName: 'Media URL',
		name: 'media_url',
		type: 'string',
		required: true,
		default: '',
		description: 'Publicly accessible URL of the media file',
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['sendMedia'] } },
		options: [
			{ displayName: 'Caption', name: 'caption', type: 'string', default: '', description: 'Caption text (not supported for audio)' },
			{ displayName: 'Filename', name: 'filename', type: 'string', default: '', description: 'Display filename (for documents)' },
			{ displayName: 'Contact ID', name: 'contact_id', type: 'number', default: 0 },
		],
	},

	// ─── SEND INTERACTIVE ────────────────────────────────────────────────────────
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number with country code',
		displayOptions: { show: { resource: ['message'], operation: ['sendInteractive'] } },
	},
	{
		displayName: 'Interactive Type',
		name: 'interactiveType',
		type: 'options',
		required: true,
		options: [
			{ name: 'Button', value: 'button' },
			{ name: 'List', value: 'list' },
		],
		default: 'button',
		displayOptions: { show: { resource: ['message'], operation: ['sendInteractive'] } },
	},
	{
		displayName: 'Body Text',
		name: 'body_text',
		type: 'string',
		required: true,
		typeOptions: { rows: 3 },
		default: '',
		description: 'Main message body text (max 1024 chars)',
		displayOptions: { show: { resource: ['message'], operation: ['sendInteractive'] } },
	},
	{
		displayName: 'Buttons (JSON)',
		name: 'buttons',
		type: 'json',
		required: true,
		default: '[{"id":"btn_1","title":"Option 1"},{"id":"btn_2","title":"Option 2"}]',
		description: 'Array of button objects: [{"id":"btn_id","title":"Button text"}] (max 3)',
		displayOptions: {
			show: { resource: ['message'], operation: ['sendInteractive'], interactiveType: ['button'] },
		},
	},
	{
		displayName: 'List Button Text',
		name: 'list_button_text',
		type: 'string',
		required: true,
		default: 'Select an option',
		description: 'Text on the list menu button (max 20 chars)',
		displayOptions: {
			show: { resource: ['message'], operation: ['sendInteractive'], interactiveType: ['list'] },
		},
	},
	{
		displayName: 'Sections (JSON)',
		name: 'sections',
		type: 'json',
		required: true,
		default: '[{"title":"Section 1","rows":[{"id":"row_1","title":"Row 1","description":"Description"}]}]',
		description: 'Array of section objects with rows',
		displayOptions: {
			show: { resource: ['message'], operation: ['sendInteractive'], interactiveType: ['list'] },
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['sendInteractive'] } },
		options: [
			{ displayName: 'Header Text', name: 'header_text', type: 'string', default: '', description: 'Optional header (max 60 chars)' },
			{ displayName: 'Footer Text', name: 'footer_text', type: 'string', default: '', description: 'Optional footer (max 60 chars)' },
			{ displayName: 'Contact ID', name: 'contact_id', type: 'number', default: 0 },
		],
	},
];
